### ISSUE TITLE
Is it possibile to delete existing artifacts?

### ISSUE THREAD

**Issue by domedellolio** [OfficeDev/PnP-Provisioning-Schema#101]
Is it possibile to delete existing artifacts like:
- Fields
- Content Types
- Lists

Thanks

**Comment by erwinvanhunen** [comment]
Hi,

No it is not possible. 

However, you can create a custom extension handler that you register in your template. It will be called during provisioning of the template. In the handler you can then remove the artifacts. This however requires that your write a C# assembly.

I wrote a blog post on how to use them here: http://www.erwinmcm.com/using-an-extensibility-provider-with-the-pnp-provisioning-engine/. I also plan to write a guidance article about it.

**Comment by domedellolio** [comment]
OK thanks
