### ISSUE TITLE
Security and optional clearscopes

### ISSUE THREAD

**Issue by KbWorks** [OfficeDev/PnP-Provisioning-Schema#114]
Hi all,

using the last schema and last sources of PNP-Site-Core.
i get a invalid template if i do not add the optional clearscopes in Security node.

If added it works like a charm. But since it is optional and differs from older templates please change.

Kr,

Paul

**Comment by PaoloPia** [comment]
Hi,
Good catch! I've fixed it (https://github.com/OfficeDev/PnP-Sites-Core/pull/723) at the engine level in the DEV branch. It will go live with the next monthly master merge.
Thanks,
Paolo
