### ISSUE TITLE
Features dependency on provisioned items

### ISSUE THREAD

**Issue by thespooler** [OfficeDev/PnP-Provisioning-Schema#117]
Might be me missing something, but I cannot see how to order the sequence of the provisioning to enable feature dependency on a provisioned item.
For example, if a feature deploys an event receiver associated to a list to be provisioned, the feature will be incorrectly activated first, then the list will be created.
I see Sequences in the schema, but then again, they can only contain root objects, not Templates.

**Comment by PaoloPia** [comment]
Hi,
The Sequences are defined in the schema, but not yet supported at the engine level. Right now, if you need to define custom artificats with specific dependencies, you should create multiple template files and apply them in a sequence by using PowerShell or C#.
