### ISSUE TITLE
Add a way to express WelcomePage

### ISSUE THREAD

**Issue by martindr** [OfficeDev/PnP-Provisioning-Schema#12]
Can we add the ability to express the welcome page url?

It equates to Web.RootFolder.WelcomePage in the API.

In our similar in-house implementation, we expressed this as a boolean on a Page element, but I think it probably makes more sense to have it as a a URI on the Site element.

Thanks.

**Comment by VesaJuvonen** [comment]
Absolute. Thanks for your suggestion and will be certainly added to the next version we will now start working.

**Comment by msgx** [comment]
Seems like the new way to define WelcomePage via `<pnp:Pages WelcomePage="SitePages/MyPage.aspx">` does not work for some reason. Have you tested this behavior?

**Comment by PaoloPia** [comment]
You need to have the page that you declare as the home page within the list of provisioned pages.I will close this one. In case of any doubt about how to use the schema and the  PnP Provisioning Engine, please refer to the Yammer network/group for PnP (http://aka.ms/OfficeDevPnPYammer). Thanks for your contribution.
