### ISSUE TITLE
XmlDocuments

### ISSUE THREAD

**Issue by martindr** [OfficeDev/PnP-Provisioning-Schema#14]
The ContentType element should support an XmlDocuments section so we can specify things like event receivers and document set details (allowedContenttypes, sharedFields).

**Comment by PaoloPia** [comment]
Since the August release of the schema we do support Document Sets. I will close this one. In case of any need about how to use the schema and the  PnP Provisioning Engine, please refer to the Yammer network/group for PnP (http://aka.ms/OfficeDevPnPYammer), as well. Thanks for your contribution.
