### ISSUE TITLE
Nested sites

### ISSUE THREAD

**Issue by martindr** [OfficeDev/PnP-Provisioning-Schema#15]
Does the schema really support nested sites, as discussed in [this Yammer thread](https://www.yammer.com/itpronetwork/#/Threads/show?threadId=538729267)?

If so, please could you explain how. If not, can that be addressed?

Thanks!

**Comment by PaoloPia** [comment]
At the schema level we support multiple sites and sequences, and I will double-check the nested sites capability. However, at the engine (PnP Provisioning Engine) we do support just one site per time. I will close this one. In case of any need about how to use the schema and the  PnP Provisioning Engine, please refer to the Yammer network/group for PnP (http://aka.ms/OfficeDevPnPYammer), as well. Thanks for your contribution.

**Comment by martindr** [comment]
It really was the schema level I was asking about (we have our own app for provisioning but want to use the PnP schema). I'm still unclear on how to express a hierarchy of subsites.
