### ISSUE TITLE
webpartpagewebpart vs WebPart

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Provisioning-Schema#34]
When I look at the documentation there seems to be webpartpagewebpart. However in the schema I'm getting 

< pnp:Pages>
        < pnp:Page Url="/home.aspx" Layout="OneColumn" Overwrite="true">
          < pnp:WebParts>
            < pnp:WebPart Title="Test" Row="1" Column="1" >
              < pnp:Contents>
                
              < /pnp:Contents>
            < /pnp:WebPart>
...

https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2015-05.md#webpartpagewebpart

Which way is the correct way?

Also an example of how to add a web part such as a search result web part would be helpful. I tried including the xml from a webpart export but it looks like  <pnp:Contents></pnp:Contents> is always required.

**Comment by olemp** [comment]
WebPart is the right way for both Pages and Files.

**Comment by PaoloPia** [comment]
Here (https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/Samples/WebPartPage.xml) you can find a sample about how to include a Web Part in a page. It is not the Search Result Web Part, but you can start from the sample we provide. In case of any need about how to use the schema and the  PnP Provisioning Engine, please refer to the Yammer network/group for PnP (http://aka.ms/OfficeDevPnPYammer), as well. Thanks for your contribution.

**Comment by dotsad** [comment]
This will only work for wiki pages, will not work for publishing pages.
