### ISSUE TITLE
New schema: what am I missing? (getting an exception)

### ISSUE THREAD

**Issue by spmcdonough** [OfficeDev/PnP-Provisioning-Schema#37]
I had code that was working without issue to save and load ProvisioningTemplate objects prior to updating to the October 2015 release. I updated to the latest PnP Core release yesterday, and now I'm getting exceptions whenever I attempt a GetTemplates() call or GetTemplate() call for a specific named template. Here's the relevant portion of the stack trace:

--------------------------------
[NullReferenceException: Object reference not set to an instance of an object.]
   OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaV201508Formatter.ToProvisioningTemplate(Stream template, String identifier) +20422
   OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaV201508Formatter.ToProvisioningTemplate(Stream template) +44
   OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplates(ITemplateFormatter formatter) +254
   Cardinal.SPonline.Provisioning.Utilities.TemplateUtilities.GetAllTemplateNames() in f:\Cardinal\Git\Cardinal.SPonline.Provisioning\Cardinal.SPonline.Provisioning.Utilities\TemplateUtilities.cs:203
   Cardinal.SPonline.Provisioning.PHA.Web.Controllers.DeleteController.Index() in f:\Cardinal\Git\Cardinal.SPonline.Provisioning\Cardinal.SPonline.Provisioning.PHA.Web\Controllers\DeleteController.cs:58
   lambda_method(Closure , ControllerBase , Object[] ) +101
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +59
--------------------------------

This type of exception gets thrown when code like the following runs:

  List<String> allTemplateNames = new List<String>();
  XMLAzureStorageTemplateProvider templateStore = GetTemplateStorageProvider();
  var formatter = XMLPnPSchemaFormatter.GetSpecificFormatter
      (Globals.TEMPLATE_SCHEMA_VERSION);
  List<ProvisioningTemplate> allTemplates = templateStore.GetTemplates(formatter);
  allTemplates.ForEach(at => allTemplateNames.Add(at.Id));
  return allTemplateNames;

Note that GetTemplateStorageProvider() is simply a helper method to return the appropriate XMLAzureStorageTemplateProvider.

If I attempt to use the latest schema formatter (XMLPnPSchemaVersion.V201508) or omit a formatter entirely in my call to GetTemplates(), the exception is thrown. If I fall back to explicitly using the May schema version (XMLPnPSchemaVersion.V201505), all of my calls work fine to load, iterate, save, etc.

I've cleaned out the backing BLOB store where I'm housing the serialized ProvisioningTemplate instances, but it doesn't seem to make much difference. As soon as I save the first ProvisioningTemplate instance, I can't perform a GetTemplates() operation to retrieve what's being stored.

What am I missing? I'd like to use the new schema if possible ...

Thanks in advance for any help you can provide!

- Sean McDonough

**Comment by spmcdonough** [comment]
Just a follow-up: as of the 10/16 release, the code is back to working as originally intended. I'm not sure what was corrected or reverted in that two week period, but I thank you!  :-)

**Comment by PaoloPia** [comment]
Unfortunately there was a bug that we fixed. I will close this one. Thanks for your contribution.

**Comment by spmcdonough** [comment]
Awesome - thank you for the follow-up and confirmation, Paolo. I love what you and the other PnP folks are putting together  :-)
