### ISSUE TITLE
OnQuickLaunch=TRUE does not work

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/PnP-Provisioning-Schema#4]
When I use this attribute on the list instace, the list is not appearing on the quicklaunch

                  OnQuickLaunch="true"

**Comment by wictorwilen** [comment]
The schema supports OnQuickLaunch on list instances, but since you write "work" I assume that you are referring to the PnP Remote Provisioning Engine; that is another GitHub repo, therefore I'm closing this issue.
