### ISSUE TITLE
Custom tokens doesn't work

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Provisioning-Schema#42]
Trying to add a custom token CompanyName as in sample:

    <pnp:Parameters>
      <pnp:Parameter Key="CompanyName">Puzzlepart</pnp:Parameter>
    </pnp:Parameters>

Tried to use {CompanyName} in ListInstance, Field and Page Properties without success. The token are not replaced.

**Comment by erwinvanhunen** [comment]
The syntax is "{parameter:CompanyName}".

**Comment by olemp** [comment]
Ah! Thanks! Would you update the samples?

**Comment by olemp** [comment]
E.g. https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/Samples/ProvisioningSchema-2015-08-FullSample-02.xml

**Comment by PaoloPia** [comment]
Samples are now fixed. Thank you!
