### ISSUE TITLE
Can you use ifs based on parameters?

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Provisioning-Schema#44]
Can you use ifs based on parameters?

For example a parameter for publishing on/off, and use this to decide whether to deploy js or html display template files

**Comment by olemp** [comment]
@erwinvanhunen

**Comment by PaoloPia** [comment]
Hi, thanks for your contribution. Unfortunately we do not support conditional statements at the schema level and/or in the PnP Provisioning Engine. I will close this one. In case of any need about how to use the schema and the  PnP Provisioning Engine, please refer to the Yammer network/group for PnP (http://aka.ms/OfficeDevPnPYammer), as well. Thanks again for your contribution.
