### ISSUE TITLE
Pages and Layouts

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Provisioning-Schema#45]
Pages are restricted to the following layouts:

 < xsd:simpleType name="WikiPageLayout">
    < xsd:annotation>
      < xsd:documentation xml:lang="en">
        The column layout of a wiki page
      < /xsd:documentation>
    < /xsd:annotation>
    < xsd:restriction base="xsd:string">
      < xsd:enumeration value="OneColumn" />
      < xsd:enumeration value="OneColumnSidebar" />
      < xsd:enumeration value="TwoColumns" />
      < xsd:enumeration value="TwoColumnsHeader" />
      < xsd:enumeration value="TwoColumnsHeaderFooter" />
      < xsd:enumeration value="ThreeColumns" />
      < xsd:enumeration value="ThreeColumnsHeader" />
      < xsd:enumeration value="ThreeColumnsHeaderFooter" />
    < /xsd:restriction>
  < /xsd:simpleType>

This makes it impossible to use custom page layouts. Should this restriction be there?

**Comment by PaoloPia** [comment]
Hi, thanks for your contribution. In schema version 201512 we added a Custom option for the WikiPageLayout. I will close this one. Thanks again for your contribution.
