### ISSUE TITLE
DefaultVieww or DefaultView = TRUE not working

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/PnP-Provisioning-Schema#5]
When I use this attribute on the view, the view is not set as default

I tried both: DefaultVieww="TRUE" or DefaultView="TRUE"

**Comment by wictorwilen** [comment]
The schema supports DefaultView albeit misspelled (but that's another reported issue) but since you write "work" I assume that you are referring to the PnP Remote Provisioning Engine; that is another GitHub repo, therefore I'm closing this issue.
