### ISSUE TITLE
Allow for multilevel xi:Include

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Provisioning-Schema#50]
Allow for multilevel xi:Include to support dividing very large files.

Very handy in Files or Pages.xml where you have loads of Pages/Files with webparts.

**Comment by olemp** [comment]
.. does this belong to Sites Core perhaps?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback, we appreciate your contribution.
However, we already support x:include in the PnP Provisioning Engine. Thus, I will close this issue.
