### ISSUE TITLE
Calculated list column fails at creation

### ISSUE THREAD

**Issue by SuleymanA** [OfficeDev/PnP-Provisioning-Schema#52]
I have tried to export a site configuration and apply the exported template to an existing site. All is working fine except for the calculated list field. I have checked the export and the formula of the calculated field in the provisioning XML contains the internal names of the fields used in the formula. 

When creating calculated fields manually, the fields are referenced by their display name like [My Field Name]. I have looked at the SchemaXml of my list using the rest api (_api/web/lists/GetByTitle('XXX')/schemaXml) and I can see that besides the Formula property there is also a property called "FormulaDisplayNames". I solved the problem by manually replacing the content of the formula with the content of "FormulaDisplayNames" in the provisioning template. The column was then created successfully. 

Problem only seems to be happening when the internal name is different then the display name, like when it contains spaces.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your contribution. We will double-check this issue at the PnP Provisioning Engine level. It is not an issue related to the PnP Provisioning Schema by itself. Thus, I will close this one and create another one in the right repo. Thanks again.
