### ISSUE TITLE
Add support for breaking site permission inheritance

### ISSUE THREAD

**Issue by lanegoolsby** [OfficeDev/PnP-Provisioning-Schema#79]
Per the conversation in Issue https://github.com/OfficeDev/PnP-Sites-Core/issues/202 I have been trying to add the Boolean for BreakRoleInheritance and I am not able to figure it out. If I try to add the element in the 2015-12 XSD and then rebuild the .CS file as instructed in the readme.md I get build errors saying "CustomAction" does not contain a definition for 'RightsSpecified'. I get this error even if I have not made any changes to the XSD templates, so this tells me that I am probably missing a step during the code generation process.

If someone wouldn't mind adding the attribute (and another Boolean attribute indicating if the rights should be copied from the parent when breaking inheritance or set fresh), I would be glad to finish the code for creating the groups.

**Comment by PaoloPia** [comment]
Added with schema 201605 and August release of the engine.
