### ISSUE TITLE
How to use this schema?

### ISSUE THREAD

**Issue by sivarajanr** [OfficeDev/PnP-Provisioning-Schema#8]
I can see here schema xsd file and generated sample files but could not found that how to use this schema? Can you please update the documentation?

**Comment by martindr** [comment]
I found this white paper helpful.

http://www.sharepoint-reference.com/Blog/Code%20Samples/Introducing%20the%20PnP%20Provisioning%20Engine.pdf

**Comment by PaoloPia** [comment]
The PnP Provisioning Schema can be used with the PnP Provisioning Engine. Yes, the referenced paper/blog should clarify the goal.
I will close it. Thanks for your interest.
