### ISSUE TITLE
Add support for a local "path" in the File attribute

### ISSUE THREAD

**Issue by MarkStokes-outlook** [OfficeDev/PnP-Provisioning-Schema#83]
This may not be a Provisioning Schema issue, but a Provisioning Engine issue, so I will duplicate this issue in both locations.

I would like to be able to add a local path to a file that needs to be provisioned by the Files section.
https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2015-12.md#file

Since the provisioning engine can "provision" Files into our site I would like to be able to structure my provisioning folder to replicate this structure.  For example, I would like to create a local folder called "_catalogs/masterpage" for my master pages and page layouts, then create local folders at "SiteAssets/Images", SiteAssets/css", "Pages", "Documents", "Pictures/Banners", etc.

This will help me to manage my deployable files, rather than a single flat file structure that will likely breakdown if I have files of the same filename that exist in different folders of my site.

**Comment by PaoloPia** [comment]
Hi Mark,
Thanks for your feedback. Actually, you can already do that and just to make an example I already do that in most of my provisioning projects. Thus, I will close this issue. Thanks again.

**Comment by MarkStokes-outlook** [comment]
Oh can you?

Could you provide an example? I didn't see anything in the docs.
