### ISSUE TITLE
Question: duplicate items from DataRows.

### ISSUE THREAD

**Issue by MarkStokes-outlook** [OfficeDev/PnP-Provisioning-Schema#86]
I want to add DataRows to my ListInstances, but when I "re-run" an ApplyTemplate job on an existing site it duplicates those rows (unlike Files which overwrote or don't). 

Can I set anything up so that it only creates those DataRows if they don't already exist?

Oh, I wonder if setting an ID property in the DataRow would cause it to not duplicate?

**Comment by PaoloPia** [comment]
Hi, in order to handle this need, you can simply create two template files (one with the artifacts, and another one with datarows). You apply both the first time, you apply the artifacts only, the second time. Actually, at the core engine level, we always add datarows, if any. Thanks.
