### ISSUE TITLE
Missing token for group-id - needed for user-field deployment

### ISSUE THREAD

**Issue by jakobnotseth** [OfficeDev/PnP-Provisioning-Schema#88]
Reported in Pnp-Sites-Core as well:
https://github.com/OfficeDev/PnP-Sites-Core/issues/503

When deploying user-fields, you sometimes want to fill in a specific group-id in UserSelectionScope.
I suggest creating a token  {groupid:<x>} , where  <X>  is either sitegroup-title, or associatedmembersgroup, associatedownersgroup, associatedvisitorsgroup.
This needs to be checked during Field-provisioning.

**Comment by erwinvanhunen** [comment]
Thanks for reporting this one. We added a groupid token, as described in https://github.com/OfficeDev/PnP-Sites-Core/pull/724. I will close this issue.
