### ISSUE TITLE
Service unavailable issue

### ISSUE THREAD

**Issue by mcquickel** [OfficeDev/PnP-Provisioning-Schema#94]
I am using the CreateSiteCollection method from a worker role. Items are being added to a service bus queue and up to three worker roles threads are spinning up new sites at the same time. As multiple sites collections are being requested for creation I start seeing the following errors. If I introduce a minute delay before each invocation then the problem seems to be greatly diminished. Thoughts?

code
==========
                var se = new OfficeDevPnP.Core.Entities.SiteEntity
                {
                    Description = site.Description,
                    Title = site.Title,
                    Url = site.Url,
                    Template = site.TemplateId,
                    Lcid = site.Lcid,
                    SiteOwnerLogin = owner,   
                    StorageMaximumLevel = site.StorageMaximumLevel,
                    StorageWarningLevel = site.StorageWarningLevel,
                    TimeZoneId = site.TimeZoneId,
                    UserCodeMaximumLevel = site.UserCodeMaximumLevel,
                    UserCodeWarningLevel = site.UserCodeWarningLevel
                };

                // Create the site collection
                var scId = tenant.CreateSiteCollection(se); 

errors 
==========
1.	The HTTP service located at http://gm.ylo001.msoprd.msft.net/tenantmgr.asmx is unavailable.
2.     System.Net.WebException: The remote server returned an error: (400) Bad Request. - {"error":"invalid_request","error_description":"AADSTS90002: No service namespace named '0c639cdc-742a-4c2d-8715-90374f336032' was found in the data store.\

**Comment by PaoloPia** [comment]
Hi,
This issue is not related to the PnP Provisioning Schema, where you are filing it. Anyhow, it could be due to throttling rules. I will close this one. If you still need support, please open an issue in the PnP-Sites-Core repo, or ask in the Office 365 Community Network (http://network.office.com). Thanks.
